### ISSUE TITLE
Can't install `GeoTrace-1.2.zip` on QGIS 3.0.1-Girona

### ISSUE THREAD

**Issue by MeijeSibbel** [lachlangrose/GeoTools#10]
Downloaded plugin from: https://plugins.qgis.org/plugins/GeoTrace/
OS: windows 10 home.

```
QGIS version
3.0.1-Girona
QGIS code revision
a86bec25eb
Compiled against Qt
5.9.2
Running against Qt
5.9.2
Compiled against GDAL/OGR
2.2.4
Running against GDAL/OGR
2.2.3
Compiled against GEOS
3.5.0-CAPI-1.9.0
Running against GEOS
3.5.0-CAPI-1.9.0 r4084
PostgreSQL Client Version
9.2.4
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.1
PROJ.4 Version
493
```

output:

```
Couldn't load plugin 'GeoTrace' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'PyQt4' 
Traceback (most recent call last):
  File "C:/OSGeo4W64/apps/qgis/./python\qgis\utils.py", line 336, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/meije/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\GeoTrace\__init__.py", line 38, in classFactory
    from .geo_trace import GeoTrace
  File "C:/OSGeo4W64/apps/qgis/./python\qgis\utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/meije/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\GeoTrace\geo_trace.py", line 31, in 
    from PyQt4.QtCore import *#QSettings, QTranslator, qVersion, QCoreApplication
  File "C:/OSGeo4W64/apps/qgis/./python\qgis\utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'PyQt4'


Python version: 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] 
QGIS version: 3.0.1-Girona Girona, a86bec25eb 

Python Path:
C:/OSGeo4W64/apps/qgis/./python
C:/Users/meije/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/meije/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/OSGeo4W64/apps/qgis/./python/plugins
C:\OSGeo4W64\bin\python36.zip
C:\OSGeo4W64\apps\Python36\DLLs
C:\OSGeo4W64\apps\Python36\lib
C:\OSGeo4W64\bin
C:\OSGeo4W64\apps\Python36
C:\OSGeo4W64\apps\Python36\lib\site-packages
C:/Users/meije/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\meije\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins
C:\Users\meije\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins
C:\Users\meije\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\shapetools\ext-libs
C:\Users\meije\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\GeoTrace\tools
C:\Users\meije\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\GeoTrace\tools
```

Reference:

*Thiele, Samuel T; Grose, Lachlan; Samsu, Anindita; Micklethwaite, Steven; Vollgger, Stefan A; et al. Solid Earth; Gottingen Vol. 8, Iss. 6,  (2017): 1241-1253.*

**Comment by lachlangrose** [comment]
I am closing this issue as the current version of geotrace has been ported to pyqt5
