### ISSUE TITLE
can not open in qgis 3.12 linux manjaro

### ISSUE THREAD

**Issue by adilhaimoura** [lachlangrose/GeoTools#15]
it is fresh installation of the plugin
I followed the instructions and installation was successfully ended ..
first time run fails due to permissions .. so I installed dependecies manually from the error report .. reluncehed Qgis again and when I click on the Icon of the plugin it gives me this error:

> 

` An error has occurred while executing Python code: 

TypeError: tuple indices must be integers or slices, not tuple 
Traceback (most recent call last):
  File "/home/adil/.local/share/QGIS/QGIS3/profiles/default/python/plugins/GeoTrace/geo_trace.py", line 188, in open_trace
    self.dlg = GeoTraceDialog(self.iface)
  File "/home/adil/.local/share/QGIS/QGIS3/profiles/default/python/plugins/GeoTrace/geo_trace_dialog.py", line 62, in __init__
    self.setup_gui()
  File "/home/adil/.local/share/QGIS/QGIS3/profiles/default/python/plugins/GeoTrace/geo_trace_dialog.py", line 95, in setup_gui
    tab_layout.addTab(self.setup_stereonet(),"Steronet")
  File "/home/adil/.local/share/QGIS/QGIS3/profiles/default/python/plugins/GeoTrace/geo_trace_dialog.py", line 151, in setup_stereonet
    stereo_main = gtstereo.GtStereo(self.canvas,self.iface)
  File "/home/adil/.local/share/QGIS/QGIS3/profiles/default/python/plugins/GeoTrace/tools/gtstereo.py", line 51, in __init__
    self.figure, self.ax = mplstereonet.subplots()
  File "/home/adil/.local/lib/python3.8/site-packages/mplstereonet/convenience_functions.py", line 107, in subplots
    return plt.subplots(nrows, ncols, sharex=sharex, sharey=sharey,
  File "/usr/lib/python3.8/site-packages/matplotlib/pyplot.py", line 1178, in subplots
    axs = fig.subplots(nrows=nrows, ncols=ncols, sharex=sharex, sharey=sharey,
  File "/usr/lib/python3.8/site-packages/matplotlib/figure.py", line 1576, in subplots
    axarr[row, col] = self.add_subplot(gs[row, col], **subplot_kw)
  File "/usr/lib/python3.8/site-packages/matplotlib/figure.py", line 1419, in add_subplot
    a = subplot_class_factory(projection_class)(self, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/matplotlib/axes/_subplots.py", line 76, in __init__
    self._axes_class.__init__(self, fig, self.figbox, **kwargs)
  File "/home/adil/.local/lib/python3.8/site-packages/mplstereonet/stereonet_axes.py", line 39, in __init__
    LambertAxes.__init__(self, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/matplotlib/projections/geo.py", line 500, in __init__
    GeoAxes.__init__(self, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/matplotlib/axes/_base.py", line 439, in __init__
    self.set_figure(fig)
  File "/usr/lib/python3.8/site-packages/matplotlib/axes/_base.py", line 581, in set_figure
    self._set_lim_and_transforms()
  File "/home/adil/.local/lib/python3.8/site-packages/mplstereonet/stereonet_axes.py", line 64, in _set_lim_and_transforms
    LambertAxes._set_lim_and_transforms(self)
  File "/usr/lib/python3.8/site-packages/matplotlib/projections/geo.py", line 64, in _set_lim_and_transforms
    self.transAffine = self._get_affine_transform()
  File "/home/adil/.local/lib/python3.8/site-packages/mplstereonet/stereonet_axes.py", line 53, in _get_affine_transform
    xscale, _ = transform.transform_point((self.horizon, 0))
  File "/usr/lib/python3.8/site-packages/matplotlib/transforms.py", line 1507, in transform_point
    return self.transform(point)
  File "/home/adil/.local/lib/python3.8/site-packages/mplstereonet/stereonet_transforms.py", line 47, in transform
    return self.transform_affine(self.transform_non_affine(ll))
  File "/home/adil/.local/lib/python3.8/site-packages/mplstereonet/stereonet_transforms.py", line 71, in transform_non_affine
    longitude = ll[:, 0:1]
TypeError: tuple indices must be integers or slices, not tuple

Python version: 3.8.1 (default, Jan 22 2020, 06:38:00) [GCC 9.2.0] 
QGIS version: 3.12.0-București București, exported 

> `

please advise!!

**Comment by lachlangrose** [comment]
Hi it looks like mplstereonet did not install... can you check in the python console whether you can import mplstereonet?

**Comment by adilhaimoura** [comment]
![Screenshot from 2020-03-10 20-34-36](https://user-images.githubusercontent.com/61996199/76347099-b7a5a680-630e-11ea-8569-81e040e82145.png)

**Comment by adilhaimoura** [comment]
Sorry Sir it is important to me to get a feed back!!
is there any thing wrong from my side?? I can resolve ??

**Comment by lachlangrose** [comment]
Sorry for the late response, can you tell me if this is working?
