### ISSUE TITLE
Cannot open GeoTrace 1.33 in QGIS 3.10 and 3.16

### ISSUE THREAD

**Issue by shaa0003** [lachlangrose/GeoTools#21]
Hi

I installed GeoTrace 1.33 through the plug-in manager in QGIS.
Then When I opened it, a python error has happened.

I tried it in MacOS 11, Windows10 and QGIS 3.10 and 3.16
I attached the python error message.
Thank you

<img width="982" alt="스크린샷 2020-11-18 오후 12 03 00" src="https://user-images.githubusercontent.com/74640783/99498116-47314800-29ba-11eb-9d23-0a0bc8b95040.png">

**Comment by luotinen** [comment]
I confirm this for 3.10 and 3.16. It gives the following Python error:

2021-02-03T13:44:57     WARNING    Traceback (most recent call last):
              File "C:/Users/lauri_000/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\GeoTrace\geo_trace.py", line 188, in open_trace
              self.dlg = GeoTraceDialog(self.iface)
              File "C:/Users/lauri_000/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\GeoTrace\geo_trace_dialog.py", line 70, in __init__
              self.setup_gui()
              File "C:/Users/lauri_000/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\GeoTrace\geo_trace_dialog.py", line 103, in setup_gui
              tab_layout.addTab(self.setup_stereonet(), "Steronet")
              File "C:/Users/lauri_000/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\GeoTrace\geo_trace_dialog.py", line 161, in setup_stereonet
              stereo_main = gtstereo.GtStereo(self.canvas, self.iface)
              File "C:\Users\lauri_000\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\GeoTrace\tools\gtstereo.py", line 51, in __init__
              self.figure, self.ax = mplstereonet.subplots()
              File "C:\Users\lauri_000\AppData\Roaming\Python\Python37\site-packages\mplstereonet\convenience_functions.py", line 108, in subplots
              squeeze=squeeze, subplot_kw=subplot_kw, **fig_kw)
              File "C:\Users\lauri_000\AppData\Roaming\Python\Python37\site-packages\matplotlib\cbook\deprecation.py", line 451, in wrapper
              return func(*args, **kwargs)
              File "C:\Users\lauri_000\AppData\Roaming\Python\Python37\site-packages\matplotlib\pyplot.py", line 1290, in subplots
              gridspec_kw=gridspec_kw)
              File "C:\Users\lauri_000\AppData\Roaming\Python\Python37\site-packages\matplotlib\cbook\deprecation.py", line 451, in wrapper
              return func(*args, **kwargs)
              File "C:\Users\lauri_000\AppData\Roaming\Python\Python37\site-packages\matplotlib\figure.py", line 1524, in subplots
              subplot_kw=subplot_kw))
              File "C:\Users\lauri_000\AppData\Roaming\Python\Python37\site-packages\matplotlib\gridspec.py", line 337, in subplots
              self[row, col], **subplot_kw)
              File "C:\Users\lauri_000\AppData\Roaming\Python\Python37\site-packages\matplotlib\figure.py", line 1402, in add_subplot
              ax = subplot_class_factory(projection_class)(self, *args, **kwargs)
              File "C:\Users\lauri_000\AppData\Roaming\Python\Python37\site-packages\matplotlib\axes\_subplots.py", line 42, in __init__
              self._axes_class.__init__(self, fig, self.figbox, **kwargs)
              File "C:\Users\lauri_000\AppData\Roaming\Python\Python37\site-packages\mplstereonet\stereonet_axes.py", line 39, in __init__
              LambertAxes.__init__(self, *args, **kwargs)
              File "C:\Users\lauri_000\AppData\Roaming\Python\Python37\site-packages\matplotlib\projections\geo.py", line 493, in __init__
              GeoAxes.__init__(self, *args, **kwargs)
              File "C:\Users\lauri_000\AppData\Roaming\Python\Python37\site-packages\matplotlib\axes\_base.py", line 496, in __init__
              self.set_figure(fig)
              File "C:\Users\lauri_000\AppData\Roaming\Python\Python37\site-packages\matplotlib\axes\_base.py", line 633, in set_figure
              self._set_lim_and_transforms()
              File "C:\Users\lauri_000\AppData\Roaming\Python\Python37\site-packages\mplstereonet\stereonet_axes.py", line 64, in _set_lim_and_transforms
              LambertAxes._set_lim_and_transforms(self)
              File "C:\Users\lauri_000\AppData\Roaming\Python\Python37\site-packages\matplotlib\projections\geo.py", line 62, in _set_lim_and_transforms
              self.transAffine = self._get_affine_transform()
              File "C:\Users\lauri_000\AppData\Roaming\Python\Python37\site-packages\mplstereonet\stereonet_axes.py", line 53, in _get_affine_transform
              xscale, _ = transform.transform_point((self.horizon, 0))
              File "C:\Users\lauri_000\AppData\Roaming\Python\Python37\site-packages\matplotlib\transforms.py", line 1518, in transform_point
              return self.transform(point)
              File "C:\Users\lauri_000\AppData\Roaming\Python\Python37\site-packages\mplstereonet\stereonet_transforms.py", line 47, in transform
              return self.transform_affine(self.transform_non_affine(ll))
              File "C:\Users\lauri_000\AppData\Roaming\Python\Python37\site-packages\mplstereonet\stereonet_transforms.py", line 71, in transform_non_affine
              longitude = ll[:, 0:1]
             TypeError: tuple indices must be integers or slices, not tuple

**Comment by luotinen** [comment]
I reinstalled but I still get this when I try to run GeoTrace: 

2021-02-03T15:52:08     WARNING    Traceback (most recent call last):
              File "C:/Users/lauri_000/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\GeoTrace\geo_trace.py", line 188, in open_trace
              self.dlg = GeoTraceDialog(self.iface)
              File "C:/Users/lauri_000/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\GeoTrace\geo_trace_dialog.py", line 70, in __init__
              self.setup_gui()
              File "C:/Users/lauri_000/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\GeoTrace\geo_trace_dialog.py", line 94, in setup_gui
              installer.Installer().install()
              File "C:\Users\lauri_000\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\GeoTrace\tools\install_dependencies.py", line 56, in install
              assert not importlib.find_loader('mplstereonet') is None, "Could not install mplstereonet. Pip output is as follows:\n%s" % out
             AssertionError: Could not install mplstereonet. Pip output is as follows:
             b'Collecting mplstereonet==0.6\r\n Using cached mplstereonet-0.6.0-py3-none-any.whl (29 kB)\r\nRequirement already satisfied: matplotlib>=1.1 in e:\\program files\\qgis 3.16\\apps\\python37\\lib\\site-packages (from mplstereonet==0.6) (3.1.3)\r\nRequirement already satisfied: numpy>=1.1 in e:\\program files\\qgis 3.16\\apps\\python37\\lib\\site-packages (from mplstereonet==0.6) (1.19.1)\r\nRequirement already satisfied: python-dateutil>=2.1 in e:\\program files\\qgis 3.16\\apps\\python37\\lib\\site-packages (from matplotlib>=1.1->mplstereonet==0.6) (2.8.1)\r\nRequirement already satisfied: kiwisolver>=1.0.1 in e:\\program files\\qgis 3.16\\apps\\python37\\lib\\site-packages (from matplotlib>=1.1->mplstereonet==0.6) (1.1.0)\r\nRequirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in e:\\program files\\qgis 3.16\\apps\\python37\\lib\\site-packages (from matplotlib>=1.1->mplstereonet==0.6) (2.4.6)\r\nRequirement already satisfied: cycler>=0.10 in e:\\program files\\qgis 3.16\\apps\\python37\\lib\\site-packages (from matplotlib>=1.1->mplstereonet==0.6) (0.10.0)\r\nRequirement already satisfied: six>=1.5 in e:\\program files\\qgis 3.16\\apps\\python37\\lib\\site-packages (from python-dateutil>=2.1->matplotlib>=1.1->mplstereonet==0.6) (1.15.0)\r\nRequirement already satisfied: setuptools in e:\\program files\\qgis 3.16\\apps\\python37\\lib\\site-packages (from kiwisolver>=1.0.1->matplotlib>=1.1->mplstereonet==0.6) (45.2.0)\r\nInstalling collected packages: mplstereonet\r\nSuccessfully installed mplstereonet-0.6.0\r\n'

**Comment by lachlangrose** [comment]
Hi, do you know which version of mplstereonet. To find this out open the python terminal by typing `ctrl alt p` then run the following command:

`import mplstereonet
mplstereonet.__version__`

this will tell you the version number. I remember there being issues with 0.6.0 so if you have this version you can try to upgrade it. 

`import subprocess
subprocess.run('pip uninstall mplstereonet')
subprocess.run('pip install mplstereonet')`

I have tested this on qgis 3.14 on windows 64 bit and the version of mplstereonet I am using is 0.6.2. Could you please let me know if this version works for you, if it does I will force this version for geotrace

**Comment by luotinen** [comment]
Python Console
Use iface to access QGIS API interface or Type help(iface) for more info
Security warning: typing commands from an untrusted source can harm your computer
import mplstereonet mplstereonet.__version__
Traceback (most recent call last):
  File "E:\Program Files\QGIS 3.16\apps\Python37\lib\code.py", line 63, in runsource
    code = self.compile(source, filename, symbol)
  File "E:\Program Files\QGIS 3.16\apps\Python37\lib\codeop.py", line 168, in __call__
    return _maybe_compile(self.compiler, source, filename, symbol)
  File "E:\Program Files\QGIS 3.16\apps\Python37\lib\codeop.py", line 99, in _maybe_compile
    raise err1
  File "E:\Program Files\QGIS 3.16\apps\Python37\lib\codeop.py", line 87, in _maybe_compile
    code1 = compiler(source + "\n", filename, symbol)
  File "E:\Program Files\QGIS 3.16\apps\Python37\lib\codeop.py", line 133, in __call__
    codeob = compile(source, filename, symbol, self.flags, 1)
  File "<input>", line 1
    import mplstereonet mplstereonet.__version__
                                   ^

**Comment by luotinen** [comment]
Oh. Now I got it. It is two rows, so:

`import mplstereonet`
`mplstereonet.__version__`
`'0.6-dev'`

**Comment by luotinen** [comment]
`import subprocess`
`subprocess.run('pip uninstall mplstereonet')`
`CompletedProcess(args='pip uninstall mplstereonet', returncode=0)`
`subprocess.run('pip install mplstereonet')`
`CompletedProcess(args='pip install mplstereonet', returncode=0)`

**Comment by luotinen** [comment]
After the above commands:

`import mplstereonet`
`mplstereonet.__version__`
`'0.6-dev'`

**Comment by luotinen** [comment]
It works! GeoTrace 1.33 launches without errors. Hurrah! Thanks. :)

(Windows 10 64-bit, QGIS 3.16.3-Hannover, GeoTrace 1.33, mplstereonet 0.6-dev)

**Comment by lachlangrose** [comment]
Great I'll close this issue then
