### ISSUE TITLE
Python error when running Cost calculator on QGIS 3.14

### ISSUE THREAD

**Issue by yukon-aik** [lachlangrose/GeoTools#23]
Good day. I have the GeoTrace installed successfully on W10, QGIS 3.14, python v3.7.

I have tried running the cost calculator using my own geological image and also tried the Bingie Bingie Survey QGIS project.
However when running the cost calculator, only "darkness" able to output a new raster while others throw the similar python error like below:

2021-03-26T14:41:24     WARNING    Traceback (most recent call last):
              File "C:/Users/ka.tan/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\GeoTrace\geo_trace_dialog.py", line 368, in run_costcalculator
              calc.run_calculator(c[0], self.cost_name.text())
              File "C:\Users\ka.tan\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\GeoTrace\tools\gttracetool.py", line 537, in run_calculator
              array = self.calc_edges(4)
              File "C:\Users\ka.tan\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\GeoTrace\tools\gttracetool.py", line 561, in calc_edges
              self.layer_to_numpy(self.layer)
              File "C:\Users\ka.tan\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\GeoTrace\tools\gttracetool.py", line 492, in layer_to_numpy
              self.arrays.append(np.rot90(array,3))
             AttributeError: 'CostCalculator' object has no attribute 'arrays'

Please can you provide help on this?

**Comment by JFitFug** [comment]
I have the same issue - anyone found a way to resolve this?

**Comment by lau089** [comment]
Same issue

**Comment by Brick095** [comment]
I am having the exact same issue.. anyone managed to solve this?
