### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by Winizqgis** [lachlangrose/GeoTools#26]
Hi,

I'd like to use GeoTrace but an error occurs during the Python code execution.

Traceback (most recent call last):
              File "C:/Users/AAA462/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\GeoTrace\geo_trace.py", line 188, in open_trace
              self.dlg = GeoTraceDialog(self.iface)
              File "C:/Users/AAA462/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\GeoTrace\geo_trace_dialog.py", line 70, in __init__
              self.setup_gui()
              File "C:/Users/AAA462/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\GeoTrace\geo_trace_dialog.py", line 94, in setup_gui
              installer.Installer().install()
              File "C:\Users\AAA462\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\GeoTrace\tools\install_dependencies.py", line 56, in install
              assert not importlib.find_loader('mplstereonet') is None, "Could not install mplstereonet. Pip output is as follows:\n%s" % out
             AssertionError: Could not install mplstereonet. Pip output is as follows:
             b'Collecting mplstereonet==0.6\r\n'

Regards

**Comment by lachlangrose** [comment]
Hi, it looks like you can't install mplstereonet, can you tell me which version of qgis you are using

**Comment by Winizqgis** [comment]
Hi, i use the Hannover release, 3.16.7.

I found your readme.md instruction to install mplstereonet, chapter "Manual install instructions for MS Windows users"
but i couldn't make it work via OSGeo4W Shell. The command lines weren't recognized.

**Comment by Winizqgis** [comment]
Hi, I asked my company IT to look for a solution.
Apparently they face the same issue during the plug in installation.

They need to identify the flux they have to whitelist. Can you please give me the informations needed ? (Sorry for the poor informations given, I'm not in IT, i'm just the messenger between you and them...^^)

**Comment by Winizqgis** [comment]
For more accuracy (deepl translation from french)  : 

IT n°1 - 1 week ago : "We have not found a way to configure a proxy on the application to allow the installation of dependencies from "files.pythonhosted.org". 
The plugin requires installing dependencies that will point to "files.pythonhosted.org". Without them, the plugin will not work."

IT n°2 - 4 days ago : "In this case, please specify which feeds you would like to see whithelisted"
